# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synoctl < Formula
  desc "Command-line Interface for devices running Synology DSM"
  homepage "https://github.com/LukeWinikates/synology-go"
  version "0.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.19/synoctl_Darwin_x86_64.tar.gz"
      sha256 "93bf726293713963269f273a75ad3b918348db187bf09969ec69d3a02ea398f9"

      def install
        bin.install "synoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.19/synoctl_Darwin_arm64.tar.gz"
      sha256 "c19eec03538a1091590078b380bfad65cf5e556a1afb228bc7f20adffb537548"

      def install
        bin.install "synoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.19/synoctl_Linux_x86_64.tar.gz"
      sha256 "9059c67365b74b9e7e8824a32122ebf2fdff5b9d591287c6108ce6af5b597f93"
      def install
        bin.install "synoctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.19/synoctl_Linux_arm64.tar.gz"
      sha256 "b881eb7285cf2448bcebc075aa79bf669b96cea913fef505d8b0962941ad9863"
      def install
        bin.install "synoctl"
      end
    end
  end
end
