# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synoctl < Formula
  desc "Command Line Interface for devices running Synology DSM"
  homepage "https://github.com/LukeWinikates/synology-go"
  version "0.0.14"

  on_macos do
    on_intel do
      url "https://github.com/LukeWinikates/synology-go/releases/download/v0.0.14/synoctl_Darwin_x86_64.tar.gz"
      sha256 "9c53cc743ddefba709d13e572168c057d9d1362629042805a1360ac3e164c325"

      def install
        bin.install "synoctl"
      end
    end
    on_arm do
      url "https://github.com/LukeWinikates/synology-go/releases/download/v0.0.14/synoctl_Darwin_arm64.tar.gz"
      sha256 "a24d6bb16a4fa63767c6454056b116ea159952a8441a2d0f6570a78f45c048cd"

      def install
        bin.install "synoctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LukeWinikates/synology-go/releases/download/v0.0.14/synoctl_Linux_x86_64.tar.gz"
        sha256 "111899b44668362244c73424b12ccb453cbc2244d24d7ff42d97ccb70ed342ee"

        def install
          bin.install "synoctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LukeWinikates/synology-go/releases/download/v0.0.14/synoctl_Linux_arm64.tar.gz"
        sha256 "6f292f93c8f20b81f422a10bbfc8062d3164198d2702967bc0d29d4e35614569"

        def install
          bin.install "synoctl"
        end
      end
    end
  end
end
