# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synoctl < Formula
  desc ""
  homepage "https://github.com/LukeWinikates/synology-go"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.11/synoctl_Darwin_x86_64.tar.gz"
      sha256 "b3564ed61dd98d3b5a7f2dcf6667847884b4342fff1ef7feaa0983e9247ebbd3"

      def install
        bin.install "synoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.11/synoctl_Darwin_arm64.tar.gz"
      sha256 "5dfbdd3c2c9654ad605c9dbcecd7f35e23175afe01d26a32e299b7e58955b24b"

      def install
        bin.install "synoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.11/synoctl_Linux_x86_64.tar.gz"
      sha256 "a465914993e5a6055cbc81d853d0f04cf467597ed3e3c7a1f0c9113888282027"

      def install
        bin.install "synoctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LukeWinikates/synology-go/releases/download/0.0.11/synoctl_Linux_arm64.tar.gz"
      sha256 "983b17736fd71c92132f48f341aa95fe113d43cebb6d54fe6a4481fbcce46504"

      def install
        bin.install "synoctl"
      end
    end
  end
end
